title: Optimal Decisions Sports Analytics Academy
email: your-email@example.com
description: Can analyzing sports data lead to insights?!
author: Ram Narasimhan
baseurl: "/sports-analytics"
url: "https://optimaldecisions.github.io"

# Social Profiles

# Add your google-analytics ID here to activate google analytics
#google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
